### ISSUE TITLE
Ecommerce price doesn't show correctly if setup fee is included

### ISSUE THREAD

**Issue by mcpacific** [websavers/WHMCS-Google-Tag-Manager#11]
dataLayer push shows:

"price":"12.95+19.95SetupFee"

I believe it should be this instead:

"price":"32.90"

**Comment by jas8522** [comment]
Which event does it correspond with?

**Comment by mcpacific** [comment]
add_to_cart, begin_checkout, and purchase.

**Comment by jas8522** [comment]
You sure about that? Because the purchase event accesses the order amount data totally separately from the rest. You can see how it's presented as 'amount' here: https://developers.whmcs.com/api-reference/getorders/

No indication that it would have setup fee like that...

**Comment by mcpacific** [comment]
Perhaps purchase, but I saw add_to_cart and begin_checkout showed the price the way I indicated above. You can put a connected GA4 property in debug and view the events as they are received by GA4.
