### ISSUE TITLE
Error: Call to a member function toNumeric() on null in /modules/addons/google_tag_manager/hooks.php:136

### ISSUE THREAD

**Issue by Zeikoo** [websavers/WHMCS-Google-Tag-Manager#14]
Hello,

WHMCS Version : 8.7.3

When addons is enabled, can't reach group page ( like : /index.php?rp=/store/vps )
Got : 

Error: Call to a member function toNumeric() on null in /modules/addons/google_tag_manager/hooks.php:136

**Comment by jas8522** [comment]
Hey @Zeikoo try v3.1 (latest main branch) out to see if that fixes it.

**Comment by Zeikoo** [comment]
Hey,

Thank you for being that fast ! 

All is working great, thank you.
