### ISSUE TITLE
Issues with registration

### ISSUE THREAD

**Issue by realprydev** [websavers/WHMCS-Google-Tag-Manager#18]
Hello,
I notice that in hooks.php, the 'region' is stated in some places but is missing in other places.
The error I am facing with registration is 'Supply your state / region.' even though it has been selected.
Please have a look into this.
Thank you.

**Comment by jas8522** [comment]
@realprydev thanks for the heads up. I've stripped validation code from this module as I don't think it's our place to be policing inputs. Try the latest code in main to see if that solves it.

This makes for the possibility of invalid register events being submit to Google, but it also ensures we're not going to prevent registrations accidentally, which is something I prefer.

**Comment by jas8522** [comment]
I'm closing this as fixed as a best effort solution. Registration events aren't going to be 100% accurate, but it's more important that we don't block legit registrations than have 100% registration event accuracy in analytics.
