### ISSUE TITLE
Foreign currency error

### ISSUE THREAD

**Issue by raphael-borges** [websavers/WHMCS-Google-Tag-Manager#4]
The gtm_format_price function does not remove the foreign currency prefix, such as Brazilian Real

**I solved this by getting the prefix variable.**
` $prefix = $vars['activeCurrency']['prefix'];`

**Changing gtm_format_price function to get all values ​​dynamically**
`function gtm_format_price($price, $currencyCode, $prefix){
    $currencyCodeUpper = strtoupper($currencyCode);
    return str_replace([$prefix, ',', ' ', $currencyCodeUpper],['','.','',''],$price);
}`

And updating the function where needed.
`'price'     => gtm_format_price($price, $currencyCode, $prefix),`

**Comment by jas8522** [comment]
Thanks @raphael-borges!

I removed the strtoupper call and used str_ireplace instead (case insensitive) and dynamically grabbed the currencycode. If you get a chance, try out the updated version to see if it works.

**Comment by raphael-borges** [comment]
Thanks! I finally had time to test.
