### ISSUE TITLE
Issue with Weebly Market Connect and Addon Module

### ISSUE THREAD

**Issue by rafaelbok** [websavers/WHMCS-Google-Tag-Manager#5]
When module tag manager is activated is getting an error in the page of weebly 
/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php:437
addons/google_tag_manager/hooks.php(123): Illuminate\Database\Eloquent\Model->offsetGet()

**Comment by jas8522** [comment]
Hey @rafaelbok 

Odd. We don't use Weebly or MarketConnect so I don't have a way to directly reproduce this.

Have you asked WHMCS support for assistance? Perhaps they can at least narrow it down to provide a more specific error. There are no references to offsetGet() in our code, so I don't really know how to narrow this down.

**Comment by rafaelbok** [comment]
Hello, i contacted them, but i have to solve myself. I just had to remove this part of the code in hooks.php
```
if (!empty($productsAdded)){ //viewcart
    foreach($productsAdded as $productAdded){
      $selectedCycle = $productAdded['billingcyclefriendly'];
      $price = (string)$productAdded['pricing']['recurring'][$selectedCycle];
      $itemsArray[] = array(                       
        'name'      => $productAdded['productinfo']['name'],
        'id'        => $productAdded['productinfo']['pid'],
        'price'     => gtm_format_price($price, $currencyCode),
        'category'  => $productAdded['productinfo']['groupname'],
        'quantity'  => 1
      );
    }
  }
```
Line 120 to 132

All still working anyway, my tagmanager get the info in the checkout so, it will not make much difference for me. tks

**Comment by jas8522** [comment]
@rafaelbok odd. Doesn't your eCommerce data in analytics no longer include details about the product purchased after commenting that out?

Also is there any indication from WHMCS which one of those values is *not* available when ordering a Weebly product? If so I can adjust that singular item.

**Comment by rafaelbok** [comment]
I have the code in my tag manager that captures this information about the purchased product and the checkout value.

I just use your module to insert tag manager in pages.

I can't tell you what the real value caused the problem.

But I realized that it also gave incompatibility with other market connect modules like SiteBuilder and SiteLock, they had the same problem as Weebly, with the module active the sales pages don't load, they only work if I remove that part of the code I mentioned. The WHMCS support staff couldn't tell me either, their support is very superficial.

Sorry, I'm using google translate LOL

**Comment by jas8522** [comment]
@rafaelbok translations are pretty good, so no worries!

I will plan to add a configuration option to enable/disable GA4 tracking code - that way you and others can do this without commenting anything out.

**Comment by jas8522** [comment]
Hey @rafaelbok I *think* the above referenced commit should fix this... it's the only part of that code that used WHMCS objects that could trigger that type of error. Now it doesn't try to cast the price object as a string, so that should fix it.

**Comment by jas8522** [comment]
@rafaelbok additionally I've added the ability to disable the DataLayer event output in https://github.com/websavers/WHMCS-Google-Tag-Manager/commit/ea0a03ace81fc267e32bf1336ccfc6cc7b884a80
