### ISSUE TITLE
Include value in Data Layer

### ISSUE THREAD

**Issue by ghost** [websavers/WHMCS-Google-Tag-Manager#6]
Is it possible to add item value or checkout total due value in data layer?

**Comment by jas8522** [comment]
Hi @domainkino,

These value are already there. See https://github.com/websavers/WHMCS-Google-Tag-Manager/blob/main/modules/addons/google_tag_manager/hooks.php

Line 130 has domain price, Lines 120 and 144 have product price -- this would be item value, no?

These values are all added to the DataLayer for both the add_to_cart and begin_checkout events.

**Comment by ghost** [comment]
Hi, thank you for your reply and time, after some hour i was able look onto the hook and able setup everything perfectly.
Can you please let me one more thing, which page or button should i fire as add to cart? cause when the product config page fired it's showing begin checkout instead add to cart.

Again thank you for this awesome addon module love it.

**Comment by jas8522** [comment]
Hey @domainkino 

add_to_cart is fired when you reach this URL: `path_to_whmcs/cart.php?a=view`

Note that if your theme does not utilize the a=view URL parameter, then it won't get tracked until you modify the code. For example some themes do away with that view cart URL and merge it into the checkout page.

**Comment by ghost** [comment]
Oh i found it, it was my theme redircting.
Thank you again brother.
