### ISSUE TITLE
Change hook for purchase action

### ISSUE THREAD

**Issue by dsadas23** [websavers/WHMCS-Google-Tag-Manager#8]
The hook ShoppingCartCheckoutCompletePage need to be changed with AfterShoppingCartCheckout, because a lot of people (including us) are not using that thank you page after order because we redirect the client to invoice after order.

With this hook AfterShoppingCartCheckout the purchase action will be sended after order.

We made this change in the hooks.php but the purchase action is not triggered.

Do you have some advaice?

Thank you!

**Comment by jas8522** [comment]
The DataLayer vars are only sent when Javascript is executed on a page loaded by a browser, so AfterShoppingCartCheckout will not work.

There are only two options:
1. Stop skipping the checkout complete page and let the module do its thing, or
2. Figure out how to send DataLayer variables to Google Tag Manager from PHP and not Javascript vars - I won't be doing this, but if you want to code it and submit a pull request with that as an optional setting, by all means!
