### ISSUE TITLE
not working on whmcs latest version

### ISSUE THREAD

**Issue by shayanxtreme** [websavers/WHMCS-Google-Tag-Manager#9]
can u fix it on whmcs latest version its not working

**Comment by jas8522** [comment]
I'm on 8.7.2 and it works fine here. Gonna have to look closer at your install.

**Comment by shayanxtreme** [comment]
yeah i added now worked but what is this 
![image](https://user-images.githubusercontent.com/59481321/235360142-767d8d03-6bb0-4efe-8ee0-40df8f55a810.png)

**Comment by jas8522** [comment]
As indicated in the readme: There is no admin or client area views for this module.

You will need to read the readme to set things up properly.
